# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint
on:
  workflow_call:
    inputs:
      paths:
        type: string
        description: |
          The paths to scan for issues, separated by commas.

          Defaults to `./src/**/*.sh,./test/**/*.sh`.
        required: false
        default: ./src/**/*.sh,./test/**/*.sh
      severity:
        type: string
        description: |
          The minimum severity to check for.

          Defaults to `style`.

          Valid options are:
            * `style`
            * `info`
            * `warning`
            * `error`
        required: false
        default: style
      exclude-issues:
        type: string
        description: |
          A comma-separated list of Shellcheck issues to exclude.

          Defaults to nothing.
        required: false
    secrets:
      github-token:
        description: |
          The token to use for making authenticated calls to the GitHub APIs.
        required: false
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      #-- Needed to clone the repository
      contents: read
    steps:
      - id: checkout-repository
        name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: true
          lfs: true
          submodules: recursive
          token: ${{secrets.github-token || secrets.GITHUB_TOKEN}}
      - id: install-shellcheck
        name: Install shellcheck
        run: |
          sudo apt update --assume-yes && sudo apt install --no-install-recommends --assume-yes shellcheck
      - id: lint
        name: Lint
        uses: Azbagheri/shell-linter@v0.8.0
        with:
          path: ${{inputs.paths}}
          severity: ${{inputs.severity}}
          exclude-issues: ${{inputs.exclude-issues}}
