# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Manual Test Scenarios
on:
  workflow_dispatch:
jobs:
  test:
    name: Test
    permissions:
      #-- Needed to update check statuses
      checks: write
      #-- Needed to clone the repository
      contents: read
    uses: ./.github/workflows/test.yaml
    secrets:
      github-token: ${{secrets.GITHUB_TOKEN}}
