# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Test Scenarios
on:
  workflow_call:
    inputs:
      features:
        type: string
        description: |
          A space-separated list of features to test.

          Defaults to all features.
        required: false
        default: "*"
      base-image:
        type: string
        description: |
          The base image to use for testing.

          Defaults to `debian:12`.
        required: false
        default: "debian:12"
      log-level:
        type: string
        description: |
          The logging level for the devcontainer CLI tool.

          Defaults to `info`.

          Valid options are:
            * `info`
            * `debug`
            * `trace`
        required: false
        default: "info"
    secrets:
      github-token:
        description: |
          The token to use for making authenticated calls to the GitHub APIs.
        required: false
jobs:
  test-scenarios:
    name: Test Scenarios
    runs-on: ubuntu-latest
    permissions:
      #-- Needed to clone the repository
      contents: read
    steps:
      - id: checkout-repository
        name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: true
          lfs: true
          submodules: recursive
          token: ${{secrets.github-token || secrets.GITHUB_TOKEN}}
      - id: setup-nodejs
        name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: v24
          token: ${{secrets.github-token || secrets.GITHUB_TOKEN}}
      - id: install-devcontainer-cli
        name: Install devcontainer CLI
        run: |
          npm install -g @devcontainers/cli
      - id: test
        name: Test
        run: |
          if [[ "${{inputs.features}}" == '*' ]]; then
            devcontainer features test --skip-autogenerated --skip-duplicated --base-image "${{inputs.base-image}}" --log-level "${{inputs.log-level}}" --project-folder "."
          else
            devcontainer features test --skip-autogenerated --skip-duplicated --features "${{inputs.features}}" --base-image "${{inputs.base-image}}" --log-level "${{inputs.log-level}}" --project-folder "."
          fi
