# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Test Global
on:
  workflow_call:
    inputs:
      log-level:
        type: string
        description: |
          The logging level for the devcontainer CLI tool.

          Defaults to `info`.

          Valid options are:
            * `info`
            * `debug`
            * `trace`
        required: false
        default: "info"
    secrets:
      github-token:
        description: |
          The token to use for making authenticated calls to the GitHub APIs.
        required: false
jobs:
  test-global:
    name: Test Global
    runs-on: ubuntu-latest
    permissions:
      #-- Needed to clone the repository
      contents: read
    steps:
      - id: checkout-repository
        name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: true
          lfs: true
          submodules: recursive
          token: ${{secrets.github-token || secrets.GITHUB_TOKEN}}
      - id: setup-nodejs
        name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: v24
          cache: npm
          token: ${{secrets.github-token || secrets.GITHUB_TOKEN}}
      - id: install-devcontainer-cli
        name: Install devcontainer CLI
        run: |
          npm install -g @devcontainers/cli
      - id: test
        name: Test
        run: |
          devcontainer features test --global-scenarios-only --project-folder "."
