# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Validate
on:
  workflow_call:
    secrets:
      github-token:
        description: |
          The token to use for making authenticated calls to the GitHub APIs.
        required: false
jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    permissions:
      #-- Needed to clone the repository
      contents: read
    steps:
      - id: checkout-repository
        name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: true
          lfs: true
          submodules: recursive
          token: ${{secrets.github-token || secrets.GITHUB_TOKEN}}
      - id: validate
        name: Validate
        uses: devcontainers/action@v1
        env:
          GITHUB_TOKEN: ${{secrets.github-token || secrets.GITHUB_TOKEN}}
        with:
          validate-only: true
          base-path-to-features: ./src/
          disable-repo-tagging: true
